#!/bin/bash
set -ex

mkdir build
cd ./build

EXTRA_ARGS=""
if [[ "${target_platform}" == osx-* ]]; then
    EXTRA_ARGS="${EXTRA_ARGS} -DCMAKE_MACOSX_RPATH:BOOL=ON"
    EXTRA_ARGS="${EXTRA_ARGS} -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"
    EXTRA_ARGS="${EXTRA_ARGS} -DCMAKE_OSX_SYSROOT:PATH=${CONDA_BUILD_SYSROOT}"
    EXTRA_ARGS="${EXTRA_ARGS} -DVMTK_BREW_PYTHON:BOOL=OFF"
    EXTRA_ARGS="${EXTRA_ARGS} -DVMTK_RENDERING_BACKEND:STRING=OpenGL2"
    EXTRA_ARGS="${EXTRA_ARGS} -DVTK_VMTK_CONTRIB:BOOL=OFF"
    EXTRA_ARGS="${EXTRA_ARGS} -DVTK_VMTK_USE_COCOA:BOOL=OFF"
fi

cmake -LAH -G "Ninja" \
    -DBUILD_DOCUMENTATION:BOOL=OFF \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_BUILD_TYPE:STRING="Release" \
    -DCMAKE_CXX_STANDARD=11 \
    -DCMAKE_CXX_STANDARD_REQUIRED=ON \
    -DCMAKE_CXX_EXTENSIONS=OFF \
    -DCMAKE_INSTALL_PREFIX:STRING=${PREFIX} \
    -DGIT_PROTOCOL_HTTPS:BOOL=ON \
    -DINSTALL_PKGCONFIG_DIR:STRING="${PREFIX}/lib/pkgconfig" \
    -DITK_LEGACY_SILENT:BOOL=ON \
    -DPython3_EXECUTABLE=${PREFIX}/bin/python \
    -DPython3_FIND_STRATEGY=LOCATION \
    -DPython3_ROOT_DIR=${PREFIX} \
    -DUSE_SYSTEM_ITK:BOOL=ON \
    -DUSE_SYSTEM_VTK:BOOL=ON \
    -DVMTK_BUILD_TESTING:BOOL=ON \
    -DVMTK_CONTRIB_SCRIPTS:BOOL=ON \
    -DVMTK_ENABLE_DISTRIBUTION:BOOL=OFF \
    -DVMTK_MINIMAL_INSTALL:BOOL=OFF \
    -DVMTK_MODULE_INSTALL_LIB_DIR:STRING="${PREFIX}/vmtk" \
    -DVMTK_PYTHON_VERSION:STRING="python${PY_VER}" \
    -DVMTK_SCRIPTS_ENABLED:BOOL=ON \
    -DVMTK_TEST_DATA_SOURCE="in-place" \
    -DVMTK_USE_RENDERING:BOOL=ON \
    -DVMTK_USE_VTK9:BOOL:BOOL=ON \
    -DVMTK_USE_SUPERBUILD:BOOL=OFF \
    -DVMTK_WITH_LIBRARY_VERSION:BOOL=OFF \
    -DVTK_LEGACY_SILENT:BOOL=ON \
    -DVTK_VMTK_CONTRIB:BOOL=ON \
    -DVTK_VMTK_WRAP_PYTHON:BOOL=ON \
    -Wno-dev \
    ${EXTRA_ARGS} \
    ..

ninja install

cat > $SP_DIR/vmtk-$PKG_VERSION.egg-info <<FAKE_EGG
Metadata-Version: 2.1
Name: vmtk
Version: $PKG_VERSION
Summary: vmtk is a collection of libraries and tools for 3D reconstruction, geometric analysis, mesh generation and surface data analysis for image-based modeling of blood vessels.
Platform: UNKNOWN
FAKE_EGG
