{% set version = "1.5.0" %}



package:
  name: vmtk
  version: {{ version }}

source:
  url: https://github.com/vmtk/vmtk/archive/6211af00372d099454acaf5d90520ddfcdf6cf96.zip
  sha256: f9e7156cc7df1b5b2906d7e3a39901b914608d49c2e257fa65a55caf84ee61d1
  patches:
    - patches/0001-OSX_CXX_Compatibility.patch
    - patches/0002-temporary-patch-for-testing-changes-to-vtkAddon.patch
    - patches/0003-Disable-joblib.patch  # [osx]
    - patches/0004-Fix-tests-for-new-vtk-version.patch
    - patches/0005-Fix-build-errors-with-VTK9.3.patch

build:
  number: 15

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - pkgconfig  # [unix]
    - cmake
    - git
    - ninja
    - setuptools  

  host:
    - python
    - vtk
    - libitk
    - libitk-devel
    - tbb-devel
    - xorg-libxfixes  # [linux]
    - llvm
    - setuptools  # [win]
    - libboost-python-devel ==1.85  # [unix]
  run:
    - python
    - future 
    - llvm
    - joblib
    - numpy 
    - h5py


test:
  source_files:
    - build/tests/*
  files:
    - test.sh
    - test.bat
    - importtests.py
  requires:
    - pytest
    - pytest-timeout
    - git
    - pip
  commands:
    - python importtests.py
    - bash test.sh  # [not win]
    - test.bat  # [win]

about:
  description: |
    The Vascular Modeling Toolkit is a collection of libraries and tools for 3D reconstruction, geometric analysis, mesh generation and surface data analysis for image-based modeling of blood vessels. VMTK can be used via its standalone interface, included as a Python or C++ library, or as an extension to the medical image processing platform 3D Slicer. By providing multiple user interfaces with various requirments of technical ability, VMTK aims to be usable by anyone with an interest in medical image processing; be they clinicians, researchers, industries, or educational institutions.
  home: www.vmtk.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details."
  doc_url: http://www.vmtk.org/documentation/
  dev_url: https://github.com/vmtk/vmtk

extra:
  recipe-maintainers:
    - ramtingh
