{% set name = "vmtk" %}
{% set version = "1.5.0" %}
{% set vtk_version = "9.1.0" %}
{% set itk_version = "5.2.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vmtk/vmtk/archive/30b0fdad5674d6f134e8a8b601bcef7917671b0a.zip
  sha256: e9f550c23c4413850cfecff92c483f27794e594bc30c55a5fa7a3960eb96d26c
  patches:
    - 0001-OSX_CXX_Compatibility.patch
    - 0002-vtkAddon-temp-fix.patch
    - 0003-DisableJoblibOnOSX.patch  # [osx]
    - 0004-Bugfixes.patch  

build:
  skip: true  # [py>310]
  number: 13

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - pkgconfig  # [unix]
    - cmake 
    - libboost-python-devel      # [not win]
    - git
    - ninja
    - setuptools  

  host:
    - python
    - vtk {{ vtk_version }}
    - libitk {{ itk_version }}
    - libitk-devel {{ itk_version }}
    - tbb-devel
    - xorg-libxfixes  # [linux]
    - llvm
    - setuptools  # [win]
    - libboost-python-devel      # [not win]
  run:
    - python
    - future 
    - vtk {{ vtk_version }}
    - libitk {{ itk_version }}
    - llvm
    - joblib
    - numpy 
    - h5py
    - libboost-python-devel      # [not win]
    


test:
  source_files:
    - build/tests/*
  files:
    - test.sh
    - test.bat
    - importtests.py
  requires:
    - pytest
    - pytest-timeout
    - git
    - pip
  commands:
    - python importtests.py
    - bash test.sh  # [not win]
    - test.bat  # [win]

about:
  description: |
    The Vascular Modeling Toolkit is a collection of libraries and tools for 3D reconstruction, geometric analysis, mesh generation and surface data analysis for image-based modeling of blood vessels. VMTK can be used via its standalone interface, included as a Python or C++ library, or as an extension to the medical image processing platform 3D Slicer. By providing multiple user interfaces with various requirments of technical ability, VMTK aims to be usable by anyone with an interest in medical image processing; be they clinicians, researchers, industries, or educational institutions.
  home: www.vmtk.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details."
  doc_url: http://www.vmtk.org/documentation/
  dev_url: https://github.com/vmtk/vmtk

extra:
  recipe-maintainers:
    - ramtingh
